### ISSUE TITLE
Problem with installing dev version

### ISSUE THREAD

**Issue by khsu15** [fstpackage/fst#101]
Trying to install the dev version and getting this error:

clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1

I've tried installing clang-omp, but it seems to be deprecated now.  Any advice on how to get this to work?

**Comment by MarcusKlik** [comment]
Hi @khsu15, thanks for reporting your problem, are you trying to install `fst` on a Mac? If so, then you are seeing the effects of missing support for _OpenMP_ on your OS. You can install support for _OpenMP_ by following [these](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac) instructions on the `data.table` repository. After installing a _OpenMP enabled clang_ and updating your `~/.R/Makevars` (as described), `fst` should install correctly.

After the next CRAN release, these steps won't be needed to get an _OpenMP_ enabled version of `fst`, because CRAN compiles packages using the _-openmp_ flag.  For the `dev` version unfortunately, this procedure will still be required.

I hope that helped solving your problem!

**Comment by khsu15** [comment]
Hi @MarcusKlik 
Yes, I am trying to install fst on a Mac.  I tried what you sent, but am still getting the same error.  Any other ideas?

**Comment by MarcusKlik** [comment]
Hi @khsu15, are you able to compile the `data.table` package correctly, or does `data.table` give you the same problems?

```r
remove.packages("data.table")
install.packages("data.table", type = "source",
    repos = "http://Rdatatable.github.io/data.table")
```

there are a [fair amount of issues](https://github.com/Rdatatable/data.table/issues?utf8=%E2%9C%93&q=is%3Aissue%20openmp) discussing the _openmp on Mac_ problem in the `data.table` package repository.  I currently have no access to a Mac, but if you can post your exact session details (using `SessionInfo()`), perhaps we can find a solution there!

**Comment by khsu15** [comment]
Hi @MarcusKlik, I am able to compile the data.table package correctly.  SessionInfo prints the following: 
`R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.5

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2        pbdZMQ_0.2-6    tools_3.4.2     withr_2.1.0     curl_3.0       
 [8] memoise_1.1.0   git2r_0.19.0    digest_0.6.12   devtools_1.13.3`

Also, don't know if this helps, but it seems like the difference while installing is that data.table uses:  `/usr/local/opt/llvm/bin/clang -fopenmp`
While installing dev fst. it uses: `clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -fopenmp`
Fst install has no reference to llvm clang

**Comment by MarcusKlik** [comment]
Hi @khsu15, thanks for testing that. Indeed, `fst` uses the `OpenMP` in `C++` code, where `data.table` only compiles `C` code with the _-openmp_. Could you try adding the following lines to the file _~/.R/Makevars_:

```bash
CC=/usr/local/opt/llvm/bin/clang -fopenmp
CXX=/usr/local/opt/llvm/bin/clang++ -fopenmp
# -O3 should be faster than -O2 (default) level optimisation ..
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include
```

note that the `CXX` line now has the _-openmp_ flag as well.

I hope that works, if not I will have access to a Mac next week and can help you further at that point!

**Comment by khsu15** [comment]
Hi @MarcusKlik,
I've solved the issue by downgrading the version of R that I was using from 3.4.2 to 3.3.3.  According to CRAN, 3.4.2 'uses Clang 4.0.0 and GNU Fortran 6.1, neither of which is supplied by Apple' and requires downloading extra packages and tools that wasn't quite working out.  Downgrading has done the trick.  Thanks for all your help, though!

**Comment by MarcusKlik** [comment]
Hi @khsu15, thanks for reporting and good to see that you can use `R 3.3.3` without problems. If you find the solution to getting your system to work with `R 3.4.2`, please let me know!

**Comment by mthomas00** [comment]
Hi @ MarkusKlik. First, thank you for the fantastic package. 

I'm having a similar problem to @khsu15, but on macOS 14.1, FST 0.8.8, R 3.5.1. I have followed the instructions for data.table and am able to get it complied, but not FST. Here is the output from sessionInfo():

`R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1`

I also tried adding the lines from your 11/10/17 comment to ~/.R/Makevars. Any suggestions on what to try next?

**Comment by MarcusKlik** [comment]
Hi @M7dgi4, thanks for reporting your issue!

Would it be possible for you to post the output of the failing build ? That way, we might get a better idea what's going wrong...

**Comment by mthomas00** [comment]
The build error is : 
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘fst’
